---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "swagger-ui.fullname" . }}
  labels:
    app: {{ template "swagger-ui.name" . }}
    chart: {{ template "swagger-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "swagger-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "swagger-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with .Values.deployment.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - name: SWAGGER_JSON
            value: /app/swagger.json
          - name: SWAGGER_JSON_URL
            value: {{ .Values.swaggerui.jsonUrl }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.httpGet.port }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
